conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [path("admin/", admin.site.urls), path("", include("core.urls"))]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms
from core.models import Car, Owner, VehicleStatus


class VehicleRegisterForm(forms.Form):
    tailwind_class = "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
    # owner
    first_name = forms.CharField(
        max_length=50, widget=forms.TextInput(attrs={"class": tailwind_class})
    )
    last_name = forms.CharField(
        max_length=50, widget=forms.TextInput(attrs={"class": tailwind_class})
    )
    email = forms.EmailField(widget=forms.EmailInput(attrs={"class": tailwind_class}))
    phone_number = forms.CharField(
        max_length=15, widget=forms.TextInput(attrs={"class": tailwind_class})
    )
    profile_photo = forms.ImageField(
        required=False, widget=forms.FileInput(attrs={"class": tailwind_class})
    )

    # car
    make = forms.CharField(
        max_length=50, widget=forms.TextInput(attrs={"class": tailwind_class})
    )
    model = forms.CharField(
        max_length=50, widget=forms.TextInput(attrs={"class": tailwind_class})
    )
    license_plate = forms.CharField(
        max_length=50, widget=forms.TextInput(attrs={"class": tailwind_class})
    )
    photo = forms.ImageField(
        required=False, widget=forms.FileInput(attrs={"class": tailwind_class})
    )


class OwnerForm(forms.ModelForm):
    class Meta:
        model = Owner
        fields = [
            "rfid",
            "first_name",
            "last_name",
            "email",
            "phone_number",
            "profile_photo",
        ]


class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = ["make", "model", "license_plate", "photo", "color"]


class VehicleStatusForm(forms.ModelForm):
    class Meta:
        model = VehicleStatus
        fields = ["status", "description"]

core/views/change_rfid.py
from django.shortcuts import render
from django.views import View
from core.utils import list_serial_ports
from django.contrib.auth.mixins import LoginRequiredMixin
from core.models import SerialPortConfiguration, Owner


class ChangeRfidView(LoginRequiredMixin, View):
    login_url = "accounts/login/"

    def get(self, request, pk):
        port = SerialPortConfiguration.objects.first()
        list_of_ports = list_serial_ports()
        context = {"list_of_ports": list_of_ports, "current_port": port.port}
        return render(request, "change_rfid.html", context)


class ChangeRfidChangeView(LoginRequiredMixin, View):
    login_url = "accounts/login/"

    def get(self, request, data, pk):
        exists = Owner.objects.filter(rfid=data).exists()

        if exists:
            return render(request, "rfid_exists.html")
        owner = Owner.objects.get(pk=pk)
        owner.rfid = data
        owner.save()
        return render(request, "successful_change.html")

core/views/home.py
from django.shortcuts import render
from django.views import View
from core.utils import list_serial_ports
from django.contrib.auth.mixins import LoginRequiredMixin
from core.models import SerialPortConfiguration


class HomePageView(LoginRequiredMixin, View):
    login_url = "accounts/login/"

    def get(self, request):
        port = SerialPortConfiguration.objects.first()
        list_of_ports = list_serial_ports()
        context = {"list_of_ports": list_of_ports, "current_port": port.port}
        return render(request, "check_in.html", context)

    def post(self, request):
        selected_port = request.POST.get("selected_port")
        port = SerialPortConfiguration.objects.first()
        port.port = selected_port
        port.save()
        list_of_ports = list_serial_ports()
        context = {"list_of_ports": list_of_ports, "current_port": port.port}
        return render(request, "check_in.html", context)

core/views/owner_vehicle_list.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from core.models import Owner, Car, VehicleStatus
from django.http.response import HttpResponse
from core.forms import VehicleRegisterForm, OwnerForm, CarForm, VehicleStatusForm
from django.contrib.auth.mixins import LoginRequiredMixin


class OwnerVehicleListView(LoginRequiredMixin, View):
    def get(self, request):
        cars = Car.objects.all().order_by("owner")

        # Set up pagination
        paginator = Paginator(cars, 10)  # Show 10 cars per page

        page_number = request.GET.get(
            "page"
        )  # Get the current page number from the URL
        try:
            cars_paginated = paginator.page(page_number)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            cars_paginated = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 999), deliver last page of results.
            cars_paginated = paginator.page(paginator.num_pages)

        context = {"cars": cars_paginated}
        return render(request, "owner_vehicle_list.html", context)


class OwnerVehicleDetailView(LoginRequiredMixin, View):
    def get(self, request, pk, car_pk):
        owner = get_object_or_404(Owner, pk=pk)
        car = get_object_or_404(Car, pk=car_pk)
        car_img_url = False
        owner_img_url = False
        if car.photo:
            car_img_url = True
        if owner.profile_photo:
            owner_img_url = True

        context = {
            "owner": owner,
            "car": car,
            "car_img_url": car_img_url,
            "owner_img_url": owner_img_url,
            "owner_pk": pk,
            "car_pk": car_pk,
        }

        return render(request, "owner_vehicle_detail.html", context)

    def post(self, request, pk, car_pk):
        owner = get_object_or_404(Owner, pk=pk)
        owner_form = OwnerForm(request.POST, request.FILES, instance=owner)

        # Initialize car and status forms with POST data
        car_forms = {}
        status_forms = {}
        for car in owner.cars.all():
            car_form = CarForm(request.POST, request.FILES, instance=car)
            status_form = VehicleStatusForm(request.POST, instance=car.vehicle_status)
            car_forms[car.pk] = car_form
            status_forms[car.pk] = status_form

        if owner_form.is_valid():
            owner_form.save()

            all_forms_valid = True
            for car in owner.cars.all():
                car_form = car_forms[car.pk]
                status_form = status_forms[car.pk]

                if car_form.is_valid():
                    car_form.save()
                else:
                    all_forms_valid = False

                if status_form.is_valid():
                    status_form.save()
                else:
                    all_forms_valid = False

            if all_forms_valid:
                return redirect("owner-vehicle-detail", pk=owner.pk)

        # If form validation fails, render the template with forms and errors
        car_details = []
        for car in owner.cars.all():
            status = car.vehicle_status
            car_details.append({"car": car, "status": status})

        context = {
            "owner": owner,
            "car_details": car_details,
            "owner_form": owner_form,
            "car_forms": car_forms,
            "status_forms": status_forms,
        }

        return render(request, "owner_vehicle_detail.html", context)

core/views/register.py
from django.shortcuts import render, redirect
from django.views import View
from core.models import Owner, Car, VehicleStatus, VehicleLog
from django.http.response import HttpResponse
from core.forms import VehicleRegisterForm
from core.models import SerialPortConfiguration
from core.utils import list_serial_ports
from django.db import IntegrityError
from django.db import transaction
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin


def extract_unique_field_name(error_message):
    # Logic to extract field name from the error message
    # This might vary based on your database backend
    # Example for SQLite
    if "UNIQUE constraint failed: core" in error_message:
        return error_message.split(".")[-1].strip()
    return "Unknown field"


class RegisterPageView(LoginRequiredMixin, View):
    def get(self, request):
        port = SerialPortConfiguration.objects.first()
        list_of_ports = list_serial_ports()
        context = {"list_of_ports": list_of_ports, "current_port": port.port}
        return render(request, "register.html", context)

    def post(self, request):
        selected_port = request.POST.get("selected_port")
        port = SerialPortConfiguration.objects.first()
        port.port = selected_port
        port.save()
        list_of_ports = list_serial_ports()
        context = {"list_of_ports": list_of_ports, "current_port": port.port}
        return render(request, "check_in.html", context)


class RegisterDetailView(View):
    def owner_data_save(self, data):
        owner = Owner.objects.create(
            rfid=data.get("rfid"),
            first_name=data.get("first_name"),
            last_name=data.get("last_name"),
            email=data.get("email"),
            phone_number=data.get("phone_number"),
            profile_photo=data.get("profile_photo"),
        )
        owner.save()
        return owner

    def car_data_save(self, data, owner, vehicle_status):
        car = Car.objects.create(
            owner=owner,
            make=data.get("make"),
            model=data.get("model"),
            license_plate=data.get("license_plate"),
            photo=data.get("photo"),
            vehicle_status=vehicle_status,
        )
        car.save()
        return car

    def get(self, request, data):
        form = VehicleRegisterForm()
        exists = Owner.objects.filter(rfid=data).exists()
        if exists:
            return render(request, "owner_exist.html")

        return render(request, "register_view.html", {"form": form, "data": data})

    def post(self, request, data):
        form = VehicleRegisterForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                # Extract the cleaned data
                first_name = form.cleaned_data["first_name"]
                last_name = form.cleaned_data["last_name"]
                email = form.cleaned_data["email"]
                phone_number = form.cleaned_data["phone_number"]
                profile_photo = form.cleaned_data["profile_photo"]
                make = form.cleaned_data["make"]
                model = form.cleaned_data["model"]
                license_plate = form.cleaned_data["license_plate"]
                photo = form.cleaned_data["photo"]

                owner = {
                    "rfid": data,
                    "first_name": first_name,
                    "last_name": last_name,
                    "email": email,
                    "phone_number": phone_number,
                    "profile_photo": profile_photo,
                }
                car = {
                    "make": make,
                    "model": model,
                    "license_plate": license_plate,
                    "photo": photo,
                }
                with transaction.atomic():
                    owner_instance = self.owner_data_save(owner)
                    vs = VehicleStatus.objects.create()
                    car = self.car_data_save(
                        data=car, owner=owner_instance, vehicle_status=vs
                    )
                    VehicleLog.objects.create(car=car)
                messages.success(request, "Your data was saved successfully!")
            except IntegrityError as e:
                # Check if the error is related to a UNIQUE constraint
                if "UNIQUE constraint" in str(e):
                    # Extract the field name from the error message
                    # This example assumes the error message contains the field name
                    # Modify the logic based on your database backend's error message format
                    field_name = extract_unique_field_name(str(e))
                    error = f"Error: The field {field_name} must be unique"

                return render(
                    request,
                    "register_view.html",
                    {"form": form, "data": data, "error": error},
                )

            return redirect("owner-vehicle-list")
        else:
            return render(request, "register_view.html", {"form": form, "data": data})

core/views/vehicle.py
from django.shortcuts import render
from django.views import View
from core.models import Owner, Car, VehicleStatus, VehicleLog
from django.http.response import HttpResponse
import serial
from core.models import SerialPortConfiguration
import time
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone


class VehiclePageView(LoginRequiredMixin, View):
    def get(self, request, data):
        exists = Owner.objects.filter(rfid=data).exists()

        if exists:
            owner = Owner.objects.get(rfid=data)
            car = Car.objects.filter(owner=owner).first()
            vl = VehicleLog.objects.filter(car=car).order_by("time_out").first()
            vs = VehicleStatus.objects.get(car=car)

            status = vs.status
            if status == "in":
                vs.status = "out"
            else:
                vs.status = "in"
            vs.save()
            if not vl.time_out:
                if vs.status == "in":
                    vl.time_in = timezone.now()
                if vs.status == "out":
                    vl.time_out = timezone.now()
            else:
                vl = VehicleLog.objects.create(car=car)
                if vs.status == "in":
                    vl.time_in = timezone.now()
            vl.save()

            context = {
                "owner": owner,
                "car": car,
                # "status": status
            }
            return render(request, "vehicle_view.html", context)
        else:
            return render(request, "owner_not_exists.html", {})

templates/base.html
{% load static %} {% load django_htmx %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>

    <link href="{% static 'css/output.css' %}" rel="stylesheet" />

    {% comment %}
    <script src="{% static 'css/ouput.css' %}"></script>
    {% endcomment %}
    <link href="{% static 'css/scan_loader.css' %}" rel="stylesheet" />
    <script src="{% static 'js/flowbite.min.js'%}"></script>
  </head>
  <style>
    [x-cloak] {
      display: none !important;
    }
  </style>
  <body>
    <div class="container max-w-7xl mx-auto">
      <div x-data="{ showMessage: true }">
        {% if messages %}
        <ul class="messages">
          {% for message in messages %}
          <li
            x-show="showMessage"
            x-init="setTimeout(() => { showMessage = false }, 2000)"
            {%
            if
            message.tags
            %}
            class="{{ message.tags }}"
            {%
            endif
            %}
          >
            <div
              class="p-4 mb-4 text-sm mt-3 text-green-800 rounded-lg bg-green-200"
              role="alert"
            >
              <span class="font-medium">Success!</span> {{ message }}
            </div>
          </li>
          {% endfor %}
        </ul>
        {% endif %}
      </div>
      {% block content %} {% endblock %}
    </div>

    <script src="{% static 'js/htmx.min.js' %}" defer></script>
    <script src="{% static 'js/alpine.min.js' %}" defer></script>
    {% django_htmx_script %}
  </body>
</html>

templates/change_rfid.html
{% extends "base.html" %} {% block content %}
<div>{% include "components/header.html" %}</div>
<div>
  <div
    hx-get="{% url 'get-rfid-change' request.resolver_match.kwargs.pk %}"
    hx-trigger="every 1s"
    hx-swap="outerHTML"
  ></div>
  <form class="max-w-sm mx-auto" id="portForm" method="post">
    {% csrf_token %}
    <label for="countries" class="block mb-2 text-sm font-medium text-gray-900"
      >Choose USB Port Of Your Scanner</label
    >

    <select
      id="ports"
      name="selected_port"
      onchange="document.getElementById('portForm').submit()"
      x-data="{selectedValue: '{{ current_port }}'}"
      class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
    >
      {% for port in list_of_ports %}
      <option
        x-bind:selected="selectedValue === '{{ port.port }}'"
        value="{{ port.port }}"
      >
        {{ port.description }}
      </option>
      {% endfor %}
    </select>
  </form>
  <div class="text-center mt-10 font-medium text-gray-600 text-xl">
    <h2>Scan New ID to change you RFID</h2>
  </div>
  <div class="flex items-center justify-center mt-20 font-medium text-gray-600">
    <h3>Ready to scan the rfid</h3>
  </div>
  <div class="mx-auto border-3 mt-10 rounded h-72 w-64 flex bg-gray-900">
    <span class="scan-loader mt-10 left-[123px] top-[100px]"></span>
  </div>
</div>
{% endblock %}

templates/check_in.html
{% extends "base.html" %} {% block content %}
<div>{% include "components/header.html" %}</div>
<div>
  <div
    hx-get="{% url 'get-rfid-home' %}"
    hx-trigger="every 1s"
    hx-swap="outerHTML"
  ></div>
  <form class="max-w-sm mx-auto" id="portForm" method="post">
    {% csrf_token %}
    <label for="countries" class="block mb-2 text-sm font-medium text-gray-900"
      >Choose USB Port Of Your Scanner</label
    >
    <select
      id="ports"
      name="selected_port"
      onchange="document.getElementById('portForm').submit()"
      x-data="{selectedValue: '{{ current_port }}'}"
      class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
    >
      {% for port in list_of_ports %}
      <option
        x-bind:selected="selectedValue === '{{ port.port }}'"
        value="{{ port.port }}"
      >
        {{ port.description }}
      </option>
      {% endfor %}
    </select>
  </form>
  <div class="text-center mt-10 font-medium text-gray-600 text-xl">
    <h2>Check IN/OUT</h2>
  </div>
  <div class="flex items-center justify-center mt-20 font-medium text-gray-600">
    <h3>Ready to scan the rfid</h3>
  </div>
  <div class="mx-auto border-3 mt-10 rounded h-72 w-64 flex bg-gray-900">
    <span class="scan-loader mt-10 left-[123px] top-[100px]"></span>
  </div>
</div>
{% endblock %}

templates/home.html
{% extends "base.html" %} {% block content %}
<div>
  {% include "components/header.html" %}
  <div>
    <form>
      <label for="choices">Choose serial port:</label>
      <select id="choices" name="choices">
        <option value="" disabled selected>Select a port</option>

        {% for value in list_of_ports %}
        <option value="{{value.port}}">{{ value.description }}</option>
        {% endfor %}
      </select>
    </form>
  </div>
  <div
    hx-get="{% url 'get-rfid-home' %}"
    hx-trigger="every 1s"
    hx-swap="outerHTML"
  >
    <a href="{% url 'vehicle-detail-view' data=data%}" class="text-amber-500">
      check status
    </a>
  </div>
</div>

{% endblock content %}

templates/logs.html
{% extends "base.html" %} {% load static %} {% block content %}
<div>{% include "components/header.html" %}</div>
<div class="w-1/4">
  <form
    method="GET"
    action=""
    class="flex flex-col space-y-4 p-4 bg-white rounded-lg shadow-md"
  >
    <label for="start_date" class="text-gray-700 font-medium"
      >Filter by Date:</label
    >
    <input
      type="date"
      id="start_date"
      name="date"
      required
      class="border border-gray-300 rounded-md p-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
    />

    <button
      type="submit"
      class="bg-blue-500 text-white font-semibold py-2 px-4 rounded-md hover:bg-blue-600 transition duration-200"
    >
      Filter
    </button>
  </form>
  <a href="{% url 'owner-logs' owner.pk %}">
    <button
      type="submit"
      class="bg-blue-500 mt-10 text-white font-semibold py-2 px-4 rounded-md hover:bg-blue-600 transition duration-200"
    >
      View all
    </button>
  </a>
</div>

<div class="mt-10">
  <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500">
      <thead
        class="text-xs text-gray-700 uppercase bg-gray-50 dark:text-gray-400"
      >
        <tr>
          <th scope="col" class="px-6 py-3">Time In</th>
          <th scope="col" class="px-6 py-3">Time Out</th>
        </tr>
      </thead>
      <tbody>
        {% for vl in logs%}
        <tr class="bg-white border-b hover:bg-gray-50">
          <td class="px-6 py-4">{{ vl.time_in}}</td>
          <td class="px-6 py-4">{{ vl.time_out}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="flex justify-center mt-6 mb-16">
    <nav aria-label="Page navigation example">
      <ul class="inline-flex -space-x-px text-sm">
        <!-- check if has previous page -->
        {% if logs.has_previous %}
        <li>
          <a
            href="?page=1"
            class="flex items-center justify-center px-3 h-8 ms-0 leading-tight text-gray-500 bg-white border border-e-0 border-gray-300 rounded-s-lg hover:bg-gray-100 hover:text-gray-700"
            >First</a
          >
        </li>
        <li>
          <a
            href="?page={{ logs.previous_page_number }}"
            class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700"
            >Previous</a
          >
        </li>
        {% endif %}
        <!-- loop of page numbers -->
        {% for num in logs.paginator.page_range %}
        <!-- this is to limit the page number shown -->
        {% if logs.paginator.num_pages > 5 %}
        <!---->
        {% if num >= logs.number|add:-2 and num <= logs.number|add:2 %}
        <!-- check current number is same as page -->
        {% if num == logs.number %}
        <li>
          <p
            class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700"
          >
            <strong>{{ num }}</strong>
          </p>
        </li>
        {% else %}
        <li>
          <a
            href="?page={{ num }}"
            class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700"
            >{{ num }}</a
          >
        </li>
        {% endif %}
        <!-- end of if current page -->

        {% endif %}
        <!---->
        {% else %}
        <!---->
        {% if num == logs.number %}
        <li>
          <p
            class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700"
          >
            <strong>{{ num }}</strong>
          </p>
        </li>
        {% else %}
        <li>
          <a
            href="?page={{ num }}"
            class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700"
            >{{ num }}</a
          >
        </li>
        {% endif %}
        <!---->
        {% endif %}

        <!-- endif of the limit -->
        {% endfor %}
        <!-- end of loop -->
        <!-- check if has next page -->
        {% if logs.has_next %}
        <li>
          <a
            href="?page={{ logs.next_page_number }}"
            class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700"
            >Next</a
          >
        </li>
        <li>
          <a
            href="?page={{ logs.paginator.num_pages }}"
            class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 rounded-e-lg hover:bg-gray-100 hover:text-gray-700"
            >Last</a
          >
        </li>
        {% endif %}
      </ul>
    </nav>
  </div>
</div>
{% endblock %}

templates/owner_exist.html
{% extends "base.html" %} {% block content %}
<div>{% include "components/header.html" %}</div>
<div class="py-10 px-20">
  <div class="flex items-center">
    <div class="w-10 h-10 mr-4">
      <svg
        fill="#ff0000"
        viewBox="0 0 1920 1920"
        xmlns="http://www.w3.org/2000/svg"
      >
        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
        <g
          id="SVGRepo_tracerCarrier"
          stroke-linecap="round"
          stroke-linejoin="round"
        ></g>
        <g id="SVGRepo_iconCarrier">
          <path
            d="M960 0c530.193 0 960 429.807 960 960s-429.807 960-960 960S0 1490.193 0 960 429.807 0 960 0Zm-9.838 1342.685c-84.47 0-153.19 68.721-153.19 153.19 0 84.47 68.72 153.192 153.19 153.192s153.19-68.721 153.19-153.191-68.72-153.19-153.19-153.19ZM1153.658 320H746.667l99.118 898.623h208.755L1153.658 320Z"
            fill-rule="evenodd"
          ></path>
        </g>
      </svg>
    </div>
    <div>
      <h2
        class="font-medium leading-6 text-gray-600 transition duration-150 ease-out hover:text-gray-900"
      >
        User is Already in the database
      </h2>
    </div>
  </div>
  <div
    class="ml-4 px-10 mt-3"
    x-data="{ redirect() { setTimeout(() => { window.location.href = '/register/'; }, 10000) } }"
    x-init="redirect()"
  >
    <div
      class="leading-6 text-gray-600 transition duration-150 ease-out hover:text-gray-900"
    >
      You will be redirected in 10 seconds...
    </div>
  </div>
</div>
{% endblock content%}

templates/owner_not_exists.html
{% extends "base.html" %} {% block content %}
<div>{% include "components/header.html" %}</div>
<div class="py-10 px-20">
  <div class="flex items-center">
    <div class="w-10 h-10 mr-4">
      <svg
        fill="#ff0000"
        viewBox="0 0 1920 1920"
        xmlns="http://www.w3.org/2000/svg"
      >
        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
        <g
          id="SVGRepo_tracerCarrier"
          stroke-linecap="round"
          stroke-linejoin="round"
        ></g>
        <g id="SVGRepo_iconCarrier">
          <path
            d="M960 0c530.193 0 960 429.807 960 960s-429.807 960-960 960S0 1490.193 0 960 429.807 0 960 0Zm-9.838 1342.685c-84.47 0-153.19 68.721-153.19 153.19 0 84.47 68.72 153.192 153.19 153.192s153.19-68.721 153.19-153.191-68.72-153.19-153.19-153.19ZM1153.658 320H746.667l99.118 898.623h208.755L1153.658 320Z"
            fill-rule="evenodd"
          ></path>
        </g>
      </svg>
    </div>
    <h2
      class="font-medium leading-6 text-gray-600 transition duration-150 ease-out hover:text-gray-900"
    >
      User not exist in the database
    </h2>
  </div>
  <div
    class="ml-4 px-10 mt-3"
    x-data="{ redirect() { setTimeout(() => { window.location.href = '/'; }, 10000) } }"
    x-init="redirect()"
  >
    <div
      class="leading-6 text-gray-600 transition duration-150 ease-out hover:text-gray-900"
    >
      You will be redirected in 10 seconds...
    </div>
  </div>
</div>
{% endblock content%}

templates/register_view.html
{% extends "base.html" %} {% block content %}
<div>{% include "components/header.html" %}</div>
<div>{{error}}</div>
<div class="px-20 font-medium leading-6 text-gray-600 text-xl">
  Register User And Vehicle Here
</div>

<form class="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="flex w-full mx-auto space-x-20 px-20 mt-10">
    <div class="w-full">
      <div>
        <h2 class="block mb-5 text-lg font-medium text-gray-900">
          Owner Information
        </h2>
      </div>
      <div class="mb-5">
        <label
          for="id_first_name"
          class="block mb-2 text-sm font-medium text-gray-900"
          >First Name</label
        >
        {{form.first_name}}
      </div>
      <div class="mb-5">
        <label
          for="id_last_name"
          class="block mb-2 text-sm font-medium text-gray-900"
          >Last Name</label
        >
        {{form.last_name}}
      </div>
      <div class="mb-5">
        <label
          for="id_email"
          class="block mb-2 text-sm font-medium text-gray-900"
          >Email</label
        >
        {{form.email}}
      </div>
      <div class="mb-5">
        <label
          for="id_phone_number"
          class="block mb-2 text-sm font-medium text-gray-900"
          >Phone Number</label
        >
        {{form.phone_number}}
      </div>
      <div class="mb-5">
        <label
          class="block mb-2 text-sm font-medium text-gray-900"
          for="id_profile_photo"
          >Profile Image</label
        >
        {{form.profile_photo}}
      </div>
    </div>
    <div class="w-full">
      <div>
        <h2 class="block mb-5 text-lg font-medium text-gray-900">
          Vehicle Information
        </h2>
      </div>
      <div class="mb-5">
        <label
          for="id_make"
          class="block mb-2 text-sm font-medium text-gray-900"
          >Make</label
        >
        {{form.make}}
      </div>
      <div class="mb-5">
        <label
          for="id_model"
          class="block mb-2 text-sm font-medium text-gray-900"
          >Model</label
        >
        {{form.model}}
      </div>
      <div class="mb-5">
        <label
          for="id_license_plate"
          class="block mb-2 text-sm font-medium text-gray-900"
          >License Plate</label
        >
        {{form.license_plate}}
      </div>
      <div class="mb-5">
        <label
          class="block mb-2 text-sm font-medium text-gray-900"
          for="id_photo"
          >Vehicle Image</label
        >
        {{form.photo}}
      </div>
      <div class="flex justify-end">
        <button
          type="submit"
          class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"
        >
          Submit
        </button>
      </div>
    </div>
  </div>
</form>

{% endblock content %}